CREATE TABLE TIPOS (
ID NUMBER NOT NULL,
NAME VARCHAR2(80 BYTE),
CONSTRAINT PK_TIPO PRIMARY KEY (ID)
);

CREATE TABLE TIPOPRODUCTO (
ID_PROD NUMBER NOT NULL, 
ID_TIPO NUMBER NOT NULL, 
CONSTRAINT PK_VIDEO PRIMARY KEY (ID_PROD, ID_TIPO),
CONSTRAINT FK_PRODC FOREIGN KEY (ID_PROD) REFERENCES PRODUCTOS(ID),
CONSTRAINT FK_TIPOPRODC FOREIGN KEY (ID_TIPO) REFERENCES TIPOS(ID)
);

ALTER TABLE CLIENTESFRECUENTES ADD (
ID_CLIENTE NUMBER NOT NULL,
CONSTRAINT FK_CLIENTEFRECUENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID));

ALTER TABLE REPRESENTANTES  ADD (
ID_RESTAURANTE NUMBER NOT NULL,
PASSWORD VARCHAR2(255 BYTE) NOT NULL,
CONSTRAINT FK_RESTREPRESENTADO FOREIGN KEY (ID_RESTAURANTE) REFERENCES RESTAURANTES(ID),
CONSTRAINT PASSRPNOTEMPTY CHECK (PASSWORD != ' '));

ALTER TABLE CLIENTESFRECUENTES ADD (
CONSTRAINT PASSCFNOTEMPY CHECK (PASSWORD != ' '));

ALTER TABLE TIPOS ADD (CONSTRAINT NOMBREUNICO UNIQUE (NAME)); 

ALTER TABLE INGREDIENTES ADD (CONSTRAINT UNICOINGREDIENTE UNIQUE (NAME)); 

SELECT * FROM PRODUCTOS;
