CREATE TABLE ZONAS (
ID NUMBER NOT NULL, 
NAME VARCHAR2(80 BYTE) NOT NULL, 
ESPACIO_ABIERTO NUMBER(1) DEFAULT 0 NOT NULL, 
CAPACIDAD NUMBER NOT NULL,
INCLUYENTE NUMBER (1) DEFAULT 0 NOT NULL, 
CONSTRAINT PK_ZONA PRIMARY KEY (ID),
CONSTRAINT BOOL_ESPACIOABIERTO CHECK (ESPACIO_ABIERTO = 1 OR ESPACIO_ABIERTO = 0), 
CONSTRAINT BOOL_INCLUYENTE CHECK (INCLUYENTE = 1 OR INCLUYENTE = 0)

);


CREATE TABLE CONDICIONESTECNICAS (
ID NUMBER NOT NULL, 
NAME VARCHAR2(80 BYTE) NOT NULL, 
CONSTRAINT PK_CONDICION PRIMARY KEY (ID));

CREATE TABLE CONDICIONZONA (
ID_ZONA NUMBER NOT NULL,
ID_CONDICION NUMBER NOT NULL, 
CONSTRAINT PK_CONDZONA PRIMARY KEY (ID_ZONA, ID_CONDICION),
CONSTRAINT FK_ZONACONDICIONADA FOREIGN KEY (ID_ZONA) REFERENCES ZONAS(ID),
CONSTRAINT FK_CONDICIONDELAZONA FOREIGN KEY (ID_CONDICION) REFERENCES CONDICIONESTECNICAS(ID));


CREATE TABLE PEDIDO (
ID NUMBER NOT NULL, 
ID_CLIENTE NUMBER NOT NULL, 
ID_PRODUCTO NUMBER NOT NULL,
FECHA TIMESTAMP(0) NOT NULL, 
CONSTRAINT PK_PEDIDO PRIMARY KEY (ID),
CONSTRAINT FK_CLIENTEPEDIDO FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID),
CONSTRAINT FK_PRODUCTOPEDIDO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID)
);

ALTER TABLE PEDIDOS ADD (
SERVIDO NUMBER(1) DEFAULT 0 NOT NULL,
CONSTRAINT BOOL_DESPACHADO CHECK (SERVIDO = 1 OR SERVIDO = 0));

ALTER TABLE ORDENES ADD (
FECHA TIMESTAMP(0) NOT NULL);

CREATE TABLE PEDIDOSDEORDEN (
ID_ORDEN NUMBER NOT NULL,
ID_PEDIDO NUMBER NOT NULL,
CONSTRAINT PK_PEDIDORDEN PRIMARY KEY (ID_ORDEN, ID_PEDIDO),
CONSTRAINT FK_ORDENPEDIDO FOREIGN KEY (ID_ORDEN) REFERENCES ORDENES(ID),
CONSTRAINT FK_PEDIDOORDEN FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID));

SELECT COUNT(*) FROM ORDENES;
