CREATE TABLE REPRESENTANTE (

ID NUMBER NOT NULL, 
NAME VARCHAR2(40 BYTE),
CONSTRAINT REPRESENTANTE_PK PRIMARY KEY (ID)


);


CREATE TABLE PRODUCTO (

ID NUMBER NOT NULL, 
NAME VARCHAR2(40 BYTE) NOT NULL,
DESCRIPCION VARCHAR2 (255 BYTE),
DESCRIPTION VARCHAR2 (255 BYTE),
COSTO_PRODUCCION NUMBER DEFAULT 0 NOT NULL,
PRECIO NUMBER NOT NULL, 
CONSTRAINT PRODUCTO_PK PRIMARY KEY (ID), 
CONSTRAINT CHECK_PRECIOPRODUCTO CHECK (PRECIO > 0), 
CONSTRAINT CHECK_COSTPORD CHECK (COSTO_PRODUCCION > 0),
CONSTRAINT CHECK_NAMENOTEMPTY CHECK (NAME NOT LIKE ' ')
);


CREATE TABLE BEBIDAS (
ID NUMBER NOT NULL, 
NAME VARCHAR2(255 BYTE) NOT NULL,
CALIENTE NUMBER(1) DEFAULT 0 NOT NULL, 
NATURAL NUMBER(1) DEFAULT 0 NOT NULL,
HIELO NUMBER(1) DEFAULT 0 NOT NULL,
SABOR VARCHAR2(255 BYTE), 
CONSTRAINT BEBIDA_PK PRIMARY KEY (ID),
CONSTRAINT BOOL_CALIENTE CHECK (CALIENTE = 1 OR CALIENTE = 0), 
CONSTRAINT BOOL_NATURAL CHECK (NATURAL = 1 OR NATURAL = 0),
CONSTRAINT BOOL_HIELO CHECK (HIELO = 1 OR HIELO = 0)
);


CREATE TABLE POSTRES (
ID NUMBER NOT NULL, 
NAME VARCHAR2(255 BYTE) NOT NULL,
SABOR VARCHAR2(255 BYTE),  
CONSTRAINT POSTRE_PK PRIMARY KEY (ID),
CONSTRAINT NOMBREEMPTY CHECK (NAME != ' ')
);

ALTER TABLE POSTRES ADD SABOR VARCHAR2(255 BYTE);


CREATE TABLE BEBIDAS (
ID NUMBER NOT NULL, 
NAME VARCHAR2(255 BYTE) NOT NULL,
CALIENTE NUMBER(1) DEFAULT 0 NOT NULL, 
NATURAL NUMBER(1) DEFAULT 0 NOT NULL,
HIELO NUMBER(1) DEFAULT 0 NOT NULL,
SABOR VARCHAR2(255 BYTE), 
CONSTRAINT BEBIDA_PK PRIMARY KEY (ID),
CONSTRAINT BOOL_CALIENTE CHECK (CALIENTE = 1 OR CALIENTE = 0), 
CONSTRAINT BOOL_NATURAL CHECK (NATURAL = 1 OR NATURAL = 0),
CONSTRAINT BOOL_HIELO CHECK (HIELO = 1 OR HIELO = 0)
);

CREATE TABLE PLATOSFUERTES (
ID NUMBER NOT NULL, 
NAME VARCHAR2(255 BYTE),
ID_ACOMPANIAMIENTO NUMBER,
CONSTRAINT PLATOFUERTE_PK PRIMARY KEY (ID),
CONSTRAINT FK_ACOMPANIAMIENTO FOREIGN KEY (ID_ACOMPANIAMIENTO) REFERENCES ENTRADAS(ID),
CONSTRAINT NAMENOTEMPTY CHECK (NAME != ' ')

);


CREATE TABLE ENTRADA (
ID NUMBER NOT NULL, 
NAME VARCHAR2(255 BYTE) NOT NULL, 
CONSTRAINT PK_ENTRADA PRIMARY KEY (ID),
CONSTRAINT NAME_EMP CHECK (NAME != ' ')

);

CREATE TABLE MENUS (

ID NUMBER NOT NULL, 
NAME VARCHAR2(255 BYTE) NOT NULL, 
PRECIO NUMBER 
);


