ALTER TABLE PLATOSFUERTES ADD (ID_PRODUCTO NUMBER NOT NULL,
CONSTRAINT FK_PRODUCTOPT FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID),
CONSTRAINT PRODNODUPLPT UNIQUE (ID_PRODUCTO)
);

ALTER TABLE BEBIDAS RENAME CONSTRAINT PRODUCTNODUPLICADOS TO PRODNODUPLBEB;

CREATE TABLE ORDEN (
ID NUMBER NOT NULL, 
IDPROD NUMBER NOT NULL,
COSTOTOTAL NUMBER NOT NULL,
CONSTRAINT PK_ORDEN PRIMARY KEY (ID),
CONSTRAINT FK_PRODCORDEN FOREIGN KEY (IDPROD) REFERENCES PRODUCTOS(ID),
CONSTRAINT COSTPOSITIVO CHECK (COSTOTOTAL > 0)
);


ALTER TABLE PRODUCTOS ADD (
ID_RESTAURANTE NUMBER NOT NULL,
CONSTRAINT FK_RESTPROD FOREIGN KEY (ID_RESTAURANTE) REFERENCES RESTAURANTES(ID));

CREATE TABLE CLIENTES (
ID NUMBER NOT NULL, 
NAME VARCHAR2(255 BYTE) NOT NULL,
MESA NUMBER NOT NULL,
CONSTRAINT PK_CLIENTE PRIMARY KEY (ID),
CONSTRAINT NAMECLNOTEMPTY CHECK (NAME != ' '));

ALTER TABLE ORDENES ADD (
ID_CLIENTE NUMBER NOT NULL,
CONSTRAINT FK_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID),
FECHA DATE NOT NULL); 


CREATE TABLE CLIENTESFRECUENTES (
ID NUMBER NOT NULL,
PASSWORD VARCHAR2(255 BYTE) NOT NULL,
CONSTRAINT PK_CLNTFRC PRIMARY KEY (ID),
CONSTRAINT FK_CLIENTEFR FOREIGN KEY (ID) REFERENCES CLIENTES(ID)); 

ALTER TABLE PRODUCTOS ADD (
CANTIDAD NUMBER NOT NULL,
CONSTRAINT CANTPOS CHECK (CANTIDAD >= 0));


ALTER TABLE MENUS ADD (
ID_ENTRADA NUMBER, 
ID_PLATOFUERTE NUMBER,
ID_POSTRE NUMBER,
ID_BEBIDA NUMBER, 
CONSTRAINT FK_MENUENTRADA FOREIGN KEY (ID_ENTRADA) REFERENCES ENTRADAS(ID),
CONSTRAINT FK_MENUBEBIDA FOREIGN KEY (ID_BEBIDA) REFERENCES BEBIDAS(ID),
CONSTRAINT FK_MENUPOSTRE FOREIGN KEY (ID_POSTRE) REFERENCES POSTRES(ID),
CONSTRAINT FK_MENUPLATOFUERTE FOREIGN KEY (ID_PLATOFUERTE) REFERENCES PLATOSFUERTES(ID)

);


ALTER TABLE MENUS ADD (
ID_RESTAURANTE NUMBER NOT NULL,
CONSTRAINT FK_MRESTAURANTE FOREIGN KEY (ID_RESTAURANTE) REFERENCES RESTAURANTES(ID)

);

CREATE TABLE PRODUCTOSSIMILARES (
ID_PRODUCTO1 NUMBER NOT NULL,
ID_PRODUCTO2 NUMBER NOT NULL,
CONSTRAINT PK_PSIMILARES PRIMARY KEY (ID_PRODUCTO1, ID_PRODUCTO2),
CONSTRAINT FK_SPROD1 FOREIGN KEY (ID_PRODUCTO1) REFERENCES PRODUCTOS(ID),
CONSTRAINT FK_SPROD2 FOREIGN KEY (ID_PRODUCTO2) REFERENCES PRODUCTOS(ID));


CREATE TABLE INGREDIENTESSIMILARES (
ID_INGREDIENTE1 NUMBER NOT NULL,
ID_INGREDIENTE2 NUMBER NOT NULL,
CONSTRAINT PK_ISIMILARES PRIMARY KEY (ID_INGREDIENTE1, ID_INGREDIENTE2),
CONSTRAINT FK_SING1 FOREIGN KEY (ID_INGREDIENTE1) REFERENCES INGREDIENTES(ID),
CONSTRAINT FK_SING2 FOREIGN KEY (ID_INGREDIENTE2) REFERENCES INGREDIENTES(ID));
